dist: trusty
sudo: false

language: node_js

services:
  - redis-server

node_js:
  - "8"
  - "6"
  - "4"

env:
  - DEFAULT_DELAY: 50

script:
  - if [ "$TRAVIS_NODE_VERSION" == "6.10.0" ]; then
      npm run lint;
    fi
  - npm run reporter
  - npm run unit
  - npm run specs
  - npm run build

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
