dist: trusty
sudo: false

language: node_js

node_js:
  - "12"
  - "10"
  - "8"

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then
      npm run lint;
    fi
  - npm run test:coverage

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

notifications:
  email: false
