language: node_js

services:
  - redis-server

node_js:
  - "6"
  - "4"

env:
  - DEFAULT_DELAY: 50

script:
  - npm run reporter
  - npm run e2e
  - npm run specs

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
